### ISSUE TITLE
zlib1.dll is missing

### ISSUE THREAD

**Issue by dorp92** [t-taniai/LocalExpStereo#1]
![image](https://user-images.githubusercontent.com/18538356/29762735-b50b6686-8bd8-11e7-91ef-4612ec2aae74.png)
After fresh clone and build.

**Comment by t-taniai** [comment]
I suspect that this is due to OpenCV dependencies. Check if OpenCV 3 binaries for the corresponding VS version are correctly installed. I assume that it is automatically installed during the first build via NuGet. To manually install it for VS 2017, try to do the following command on Package Manager console:
PM> Install-Package opencv.win.native -Version 320.1.1-vs141
See also https://www.nuget.org/packages/opencv.win.native/320.1.1-vs141

**Comment by dorp92** [comment]
![image](https://user-images.githubusercontent.com/18538356/29764191-ded8036a-8bde-11e7-9420-cf46243b3295.png)
The packages seem to be installed correctly.
 I solved this problem by copying the zlib1.dll from somewhere else in my computer to the "Realse" folder,
But it's workaround not a proper solution.

**Comment by t-taniai** [comment]
I think I fixed this issue. The OpenCV package that I initially used did not provide zlib1.dll. (On my computer the program was calling an external DLL file for another application). Thus, I changed to use another OpenCV build (3.1.0 built on x64 with vc140). Correspondingly, I have downgraded the version of the platform toolset from vc141 (VS 2017) to vc140 (VS 2015). If your VS2017 has not been installed with the VC++ 2015 vc140 toolset option, you need to add it by Visual Studio Installer.

**Comment by dorp92** [comment]
Now it is working fine, thanks.

**Comment by t-taniai** [comment]
Thanks for your report!!
