### ISSUE TITLE
How do you bulid a graph

### ISSUE THREAD

**Issue by xxl755** [t-taniai/LocalExpStereo#15]
Dear author:
   The function of expansionMoveBK in FastGCStereo.h used the function of add_tweights and add_edge in Graph Class.In my opioin, the add_edge is the way to set a t_link to the graph and the add_tweights is the way to set a n_link to the graph.So it's make me feel confused that the code mixed two functions in function  expansionMoveBK.The paper didn't explain how to build the graph,so i can't read the code. My specific question have written in the annotating codes below.

The part of source code of expansionMoveBK:
double expansionMoveBK(updateMask, Plane label1,  region,  proposalCosts,  mode = 0):
~~
~~
   for (int y = 0; y < region.height; y++){
			for (int x = 0; x < region.width; x++){
				int s = y*region.width + x;                      **//I think it's building two links from node s to the source and the terminal.**
				graph.add_tweights(s, subCurrent.at<float>(y, x), proposalCosts.at<float>(y, x));
~~
~~
  for (int y = 0; y < region.height; y++){
			for (int x = 0; x < region.width; x++){
				int s = y*region.width + x;
				graph.add_tweights(s, subCurrent.at<float>(y, x), proposalCosts.at<float>(y, x));

				bool x0 = x == 0;
				bool x1 = x == region.width - 1;
				bool y0 = y == 0;
				bool y1 = y == region.height - 1;

				if (x0 || x1 || y0 || y1)
				{
					cv::Point ps = cv::Point(x, y) + region.tl();
					for (int k = 0; k < stereoEnergy->neighbors.size(); k++)
					{
						cv::Point pt = ps + stereoEnergy->neighbors[k];
						if (region.contains(pt))
							continue;
						if (imageDomain.contains(pt) == false)
							continue;

						// pt is always label0;**why the pt is always label0?**
						float _cost00 = stereoEnergy->computeSmoothnessTerm(currentLabeling.at<Plane>(ps), currentLabeling.at<Plane>(pt), ps, k, mode);
						float _cost10 = stereoEnergy->computeSmoothnessTerm(label1, currentLabeling.at<Plane>(pt), ps, k, mode);

						graph.add_tweights(s, _cost00, _cost10);// **i don't understand why we have to rebuild two t-links**  
					}
				}
			}
		}
   
		// ee <-> ge
		// ***
		// **@
		// ***
		for (int y = 0; y < region.height; y++){
			for (int x = 0; x < region.width - 1; x++){
				int i = y*region.width + x;
				int j = y*region.width + x + 1;
				float B = cost10[StereoEnergy::NB_GE].at<float>(y, x);
				float C = cost01[StereoEnergy::NB_GE].at<float>(y, x);
				float D = cost00[StereoEnergy::NB_GE].at<float>(y, x);
				graph.add_edge(i, j, std::max(0.f, B + C - D), 0); **// i think it's building the n_links ,but don't know why we set the value at  std::max(0.f, B + C - D)**
				graph.add_tweights(i, C, 0);**// the old question why we rebulid the t_links and don' know how to set the value.** 
				graph.add_tweights(j, D - C, 0);
			}
		}
~~
~~

**Comment by t-taniai** [comment]
> In my opioin, the add_edge is the way to set a t_link to the graph and the add_tweights is the way to set a n_link to the graph.

The usage of the max flow code is provided by the authors of the software. Please consult the external README of the max flow. Your understanding about add_tweights and add_edge seems opposite.

Basically, the add_tweights is to add a cost at a node-to-terminal edge in the st-graph. The add_edge is to add an edge between two nodes. Note that the former can be called more than once and costs are accumulated, while the latter can be called only once for each pair of nodes.

The graph construction is basically the same as that of the original alpha expansion [8], so please consult their paper for the graph construction. I think you are misunderstanding about graph cuts. While unary terms are usually directly expressed as s-to-node and node-to-t edges, pairwise terms are decomposed into node-to-node edges AND s-to-node and node-to-t edges. This is explained in the alpha expansion paper. Table 2 in [24] also explains such decomposition.

Our graph construction is slightly different from the pure expansion move because of the treatment of pairwise terms across the border of a cell. In the code, pixel pairs s and t are searched. In the first block, we search for pairs such that s is in a cell and t is outside the cell. The label 1 (proposal label) of t is thus invalid and t is forced at the current label. This means that the pairwise function f(s,t) becomes a unwary term at s, as unary(s) = f(s,label0-of-t).

These are explained in the footnote 3 in the paper.

Best,
Tatsunori
