### ISSUE TITLE
using new images to generate disparity image

### ISSUE THREAD

**Issue by zhangxuanaj** [t-taniai/LocalExpStereo#4]
Hi，
I want to use my own images（left image and right） to generate disparity image by your code（MidV2）， what parameters should I modify in the info.txt? Thank you very much!@t-taniai

**Comment by t-taniai** [comment]
An info.txt file defines how to interpret intensities of groundtruth.png as disparities.
The file holds two numbers, e.g.,
-----
4
59
-----
The first number (say, S) is used to decode intensity-groundtruth.png where its intensities are divided by S to get disparities. The second number (say, D) defines the disparity search range to be [0, D-1]. It can also be provided by the -ndisp command-line argument.

For your question, when you have only left and right images without groundtruth, you don't have to create the info.txt file. Instead, when you run the program, add an argument of " -ndisp xxx" where xxx is basically your guess of the maximum disparity between left and right images.

**Comment by zhangxuanaj** [comment]
Thanks very much! But I have another question after according to your instruction to add an argument of "-ndisp xxx", that is, when I ran the code with my images, I found the column “all” of the output was "-nan(ind)", and it took a long time, at the same time, the quality of "disp0.pfm" is very poor. So, I would like to ask， is this because my image size is too large（2352×1728） or the -ndisp is not accurate enough ？

**Comment by t-taniai** [comment]
For "-nan(ind)" output: Since you are not providing ground truth, error rates in the log file will be invalid values. Don't care about them.

For poor results, both the large image size and inaccurate ndisp are possible reasons.
For large size images, 1) I suggest to modify grid cell sizes from fixed-size to rational-size.
```
// in MidV2 (before)
stereo.addLayer(5, { prop1, prop4, prop2 });
stereo.addLayer(15, { prop3, prop4 });
stereo.addLayer(25, { prop3, prop4 });
```
```
// in MidV2 (after),
int w = imL.cols;
stereo.addLayer(int(w * 0.01), { prop1, prop4, prop2 });
stereo.addLayer(int(w * 0.03), { prop3, prop4 });
stereo.addLayer(int(w * 0.09), { prop3, prop4 });
```
2) Also, using a larger "-filterRadious" (matching window size) in cmdline might be better. "-smooth_weight" should be accordingly tuned.
3) You should also consider using matching costs by MC-CNN (ie, settings for MidV3). I recently released a simple python code [MC-CNN-Chainer](https://github.com/t-taniai/mc-cnn-chainer) for easily producing cost volume files by MC-CNN.

To choose a good ndisp, please pick up a point in the scene that is closest to the camera and visible in the both images. Then, calculate the difference of x coordinates of the corresponding points in the left and right images (ie, ndisp=x_l - x_r).

Also, please make sure that the scene does not contain negative disparities. Otherwise, you need to specify the "minimum disparity" value for some class constructors (eg, FastGCStereo, RandomProposer) in the code. It is set to 0 by default.

**Comment by Doubledeny** [comment]
Hi, I want to run the code but can't download the Adirondack (1.2 GB). Please give me another download link. Thank you very much.

**Comment by t-taniai** [comment]
The link is provided via Google Drive and is still valid. Please check your browser.

**Comment by Doubledeny** [comment]
Hi, I have tried using Google, Firefox and IE but still can't download the Adirondack (1.2 GB). So can you send it to my email? My email is 2359968005@qq.com. Thank you very much.

**Comment by t-taniai** [comment]
I guess you are accessing from China. If so, then Google's services do not work for you.
Unfortunately, the file is too big to send via email, and I currently do not have other way of uploading such big files.

I suggest you to make these files by yourself. 
- The stereo data is originally from Middlebury benchmark V3 (http://vision.middlebury.edu/stereo/submit3/, half resolution).
- Cost volume files can be produced by the original MC-CNN code (with an cmdline option of "-sm_terminate cnn" (https://github.com/jzbontar/mc-cnn).
- Cost volume files can also be produced by my MC-CNN-Chainer code (https://github.com/t-taniai/mc-cnn-chainer)

**Comment by luomomo** [comment]
Hi,thank for your great work. I have test the code and it really have a good result when dodual set to 1.
 But  I meet some problems when learning this project. 
First,why there is no xx.acrt in Middv2 the same as in Middv3, but it can have a disparity result? Which part creats the DSI volumn?
Second,if I want to use other method 's DSI ,I use the function in your project` saveMatBinary`,but I crash .And when I try to debug to figure out why ,I find when the project loads your xx.acrt 
![image](https://user-images.githubusercontent.com/29419293/56413438-1529a280-62ba-11e9-9882-f89233fc1adc.png)
but  after loading mine
![image](https://user-images.githubusercontent.com/29419293/56413485-3db19c80-62ba-11e9-8fa1-6b4d4b714305.png)
Did I do something wrong when I try to save the disparity cost volumn? I thought I just need to save the W*H*Channels（or dims?）directly......
How do I can test this with other data set and cost calculation method?

**Comment by t-taniai** [comment]
For the first question, the MiddV2 mode does not use external cost volumes. Instead, the algorithm internally computes matching costs on-the-fly using Equation 9 based on pixel intensity and gradient differences. In the code, the matching costs are computed in the following function.
https://github.com/t-taniai/LocalExpStereo/blob/b2d491a2ba6176e7cef4db7a5f657b60ddf692b2/LocalExpansionStereo/StereoEnergy.h#L694
In the MiddV3 mode, on the other hand, the algorithm use external matching cost volumes (saved as *.acrt files), which are actually sigmoid outputs of a neural network (MC-CNN-acrt). To answer your question, the MiddV2 mode does output a disparity map using classical raw matching cost, which is more prone to radiometric differences, mis-rectification (calibration), etc. than neural-net based matching costs.

For the second question, I found a bug in my saveMatBinary and writeMatBinary code. The crash seems to be due to the file format difference: *.acrt contains only the data chunk but the files saved by saveMatBinary and writeMatBinary contains the header information (height, width, type) before the data chunk. Unlike the reader functions, saveMatBinary and writeMatBinary have no option to choose if we save the header or not (I should have added such options to the writers too). I will later fix the code but for now you can simply delete the following lines
https://github.com/t-taniai/LocalExpStereo/blob/b2d491a2ba6176e7cef4db7a5f657b60ddf692b2/LocalExpansionStereo/Utilities.hpp#L158-L160
and make your cost volume files again (also be careful about the type of Mat. It seems you are using CV_16U-typed mats. The algorithm accepts only CV_32F mats). 
For loading the cost volumes, use the lines below
https://github.com/t-taniai/LocalExpStereo/blob/b2d491a2ba6176e7cef4db7a5f657b60ddf692b2/LocalExpansionStereo/main.cpp#L353-L355

**Comment by luomomo** [comment]
Thank you for your prompt reply! I will try it!
